name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
  
  deploy_dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: 'mjuliani.com.br'
    needs: build
    steps:
      - name: Script 1
        run: echo Script DEV

  deploy_hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
      url: 'mjuliani.com.br'
    needs: deploy_dev
    steps:
      - name: Script 1
        run: echo Script HMG

  deploy_prod:
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: 'mjuliani.com.br'
    needs: deploy_hmg
    steps:
      - name: Script 1
        run: echo Script PROD

